version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todos_db
      POSTGRES_USER: todos_user
      POSTGRES_PASSWORD: todos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/src/database/migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - todos-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todos_user -d todos_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  migrations:
    image: flyway/flyway:latest
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todos-network
    volumes:
      - ./apps/api/src/database/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/todos_db
      FLYWAY_USER: todos_user
      FLYWAY_PASSWORD: todos_password
    command: migrate
    restart: "no"

volumes:
  postgres_data:
    driver: local

networks:
  todos-network:
    driver: bridge
